### PR TITLE
Added support for the editor buttons

### PR DESCRIPTION
**Pull request by pmagictech**
Just added a second optional parameter to the DataTable::of. Its default value is `'id'`.

### CODE REVIEW

**Comment by hermawanramadhan** [comment]
Hello. Thanks for contributing. 

That's was great! I'll review and test later..

are you already test and use this code and working fine?

**Comment by pmagictech** [comment]
Yeah, I have actually used it on an intranet setup. You can review and test it. Let me know if you encounter any issues with it.

**Comment by hermawanramadhan** [comment]
sorry late response. 

after I review and thinking. I can't accept this pull request, the reason :

1. your code looks incomplete. you said: added a second optional parameter.. I didn't see this on last your pull request.. are you sure have added this? and are you sure already test this code (last pull maybe different on your local project) ? 
2. looks like your code doesn't meet for general purpose (just what you need for your project?). 
3. are your code tested for all case? minimal case for all feature for this library on [documentation](https://codeigniter4-datatables.hermawan.dev/) ? like if we use join, subquery, etc..
4. This is my opinion. If want to make "Editor" library. maybe better if this "Editor" has Separated library or Class.

**Comment by pmagictech** [comment]
Hello @hermawanramadhan,

I have worked issue you mentioned. Please go through my latest update and let me if you encounter any other issues with the update.

**Pull request closed without merging**
